# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Steve Bottos
tagline:          Machine Learning Engineer
description:      bottos.steve@gmail.com
url:              http://stevebottos.github.io
baseurl:          /

author:
  name:           Steve Bottos
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com
